-- ºÎ¼­Å×ÀÌºíÀÇºÎ¼­ÀÌ¸§Ä®·³¿¡¼­?°ú?±ÛÀÚÀÇÀ§Ä¡¸¦­t·ÂÇÏ¿©¶ó
SELECT * FROM DEPARTMENT;
SELECT DNAME, INSTR(DNAME, '°ú') FROM DEPARTMENT;

-- ±³¼öÅ×ÀÌºí¿¡¼­ Á÷±ÞÄ®·³ÀÇ ¿ÞÂÊ¿¡ "*? ¹®ÀÚ¸¦ »ðÀÔÇÏ¿© 10¹ÙÀÌÆ®·Î Ãâ·ÂÇÏ°í
-- ±³¼ö¾ÆÀÌµðÄ®·³Àº ¿À¸¥ÂÊ¿¡ "+" ¹®ÀÚ¸¦ »ðÀÔÇÏ¿© 12¹ÙÀÌÆ®·Î Ãâ·ÂÇÏ¿©¶ó
SELECT * FROM PROFESSOR;
SELECT 
    POSITION, LPAD(POSITION,10, '*') LP,
    USERID, RPAD(USERID, 12, '+') 
FROM PROFESSOR; 

-- ÇÐ»ý Å×ÀÌºí¿¡¼­ ÇÐ»ý IDÀÇ µÞÀÚ¸® µÎ±ÛÀÚ¸¦ *·Î º¯°æ ÀüÈ­¹øÈ£ µÞ ¼¼ÀÚ¸®¸¦ *·Î º¯°æ
-- ÀüÈ­¹øÈ£ µÞÀÚ¸®¸¦ * º¯°æ
-- IDÀÇ µÞÀÚ¸® µÎ±ÛÀÚ¸¦ *·Î º¯°æ >> ÀÚ¸´¼ö¸¦ 12ÀÚ¸®·Î Ã¤¿ì±â

-- INSTR, SUBSTR, LENGHT

SELECT * FROM STUDENT;
SELECT 
    USERID,
    SUBSTR(USERID, 0, LENGTH(USERID)-2) || '***' RESULT1,
    RPAD(SUBSTR(USERID, 0, LENGTH(USERID)-2),12,'*') RESULT2,
    TEL,
    SUBSTR(TEL, 0, LENGTH(TEL)-3) || '***' RESULT3
FROM STUDENT;

-- ±³¼öÅ×ÀÌºí¿¡¼­ 101ÇÐ°ú ±³¼öÀÇ ÀÏ±ÞÀ» °è»ê(¿ù±Ù¹«ÀÏÀº22ÀÏ)ÇÏ¿© ¼Ò¼öÁ¡ Ã¹Â°ÀÚ¸®¿Í 
-- ¼ÂÂ°ÀÚ¸®¿¡¼­ ¹Ý¿Ã¸² ÇÑ °ª°ú ¼Ò¼ýÁ¡ ¿ÞÂÊ Ã¹Â°ÀÚ¸®¿¡¼­ ¹Ý¿Ã¸² ÇÑ °ªÀ» Ãâ·ÂÇÏ¿©¶ó
SELECT * FROM PROFESSOR;
SELECT 
    SAL ,
    SAL / 22,
    ROUND(SAL / 22),
    ROUND(SAL / 22, 2),
    ROUND(SAL / 22, -1)
FROM PROFESSOR
WHERE DEPTNO = 101;

-- ±³¼öÅ×ÀÌºí¿¡¼­101ÇÐ°ú±³¼öÀÇÀÏ±ÞÀ»°è»ê(¿ù±Ù¹«ÀÏÀº22ÀÏ)ÇÏ¿©¼Ò¼öÁ¡«QÂ°ÀÚ¸®¿Í¼ÂÂ°ÀÚ¸®¿¡¼­
--  ‡»èÀ™°ª°ú¼Ò¼ýÁ¡¿ÞÂÊ«QÂ°ÀÚ¸®¿¡¼­ ‡»èÀ™°ªÀ»­t·ÂÇÏ¿©¶ó
SELECT 
    SAL ,
    SAL / 22,
    TRUNC(SAL / 22),
    TRUNC(SAL / 22, 2),
    TRUNC(SAL / 22, -1)
FROM PROFESSOR
WHERE DEPTNO = 101;

SELECT TO_DATE('2022', 'YYYY') + 2022 FROM DUAL;

-- ±³¼ö¹øÈ£°¡9908ÀÎ±³¼öÀÇÀÔ»çÀÏÀ»±âÁØÀ¸·ÎÀÔ»ç30ÀÏÈÄ¿Í60ÀÏÈÄÀÇ³¯Â¥¸¦­t·ÂÇÏ¿©¶ó
SELECT * FROM PROFESSOR;
DESC PROFESSOR;

SELECT 
    PROFNO, 
    NAME, 
    HIREDATE,
    HIREDATE + 30,
    HIREDATE + 60
FROM PROFESSOR
WHERE PROFNO = 9908;

SELECT SYSDATE() FROM DUAL;

-- ÀÔ»çÇÑÁö ÀÔ»çÇÑÁö + 17³â
-- 120°³¿ù¹Ì¢ÀÎ±³¼öÀÇ±³¼ö¹øÈ£, ÀÔ»çÀÏ, ÀÔ»çÀÏ·ÎºÎÅÍÂnÀçÀÏ±îÁöÀÇ°³¿ù¼ö, ÀÔ»çÀÏ¿¡¼­6°³¿ùÈÄÀÇ³¯Â¥¸¦­t·ÂÇÏ¿©¶ó
SELECT * FROM PROFESSOR;
SELECT PROFNO, NAME, 
    HIREDATE,
    HIREDATE + 17 * 365,
    ADD_MONTHS(HIREDATE, 17 * 12 ),
    ROUND(MONTHS_BETWEEN(SYSDATE, ADD_MONTHS(HIREDATE, 17 * 12 ))) "°³¿ù¼ö",
    ADD_MONTHS(ADD_MONTHS(HIREDATE, 17 + 12),6) ÀÔ»ç6°³¿ùÈÄ
FROM PROFESSOR;

-- ¿À´ÃÀÌ¼ÓÀ™´ÞÀÇ¸¶Áö¸·³¯Â¥¿Í´Ù°¡¿À´ÂÀÏ¿äÀÏÀÇ³¯Â¥¸¦­t·ÂÇÏ¿©¶ó
-- ¿äÀÏ 1: ÀÏ¿äÀÏ, 2: ¿ù¿äÀÏ ~~ 7 : Åä¿äÀÏ
--    NEXT_DAY(SYSDATE, 'ÀÏ'),
--    NEXT_DAY(SYSDATE, 'ÀÏ¿äÀÏ')
SELECT 
    SYSDATE,
    LAST_DAY(SYSDATE),
    NEXT_DAY(SYSDATE, 1),
--    NEXT_DAY(SYSDATE, 'ÀÏ'),
--    NEXT_DAY(SYSDATE, 'ÀÏ¿äÀÏ')
    NEXT_DAY(SYSDATE, 7)
FROM DUAL;

-- 101¹øÇÐ°ú±³¼öµéÀÇÀÔ»çÀÏÀ»ÀÏ, ¿ù, ³âÀ»±âÁØÀ¸·Î¹Ý¿Ã¸²ÇÏ¿©­t·ÂÇÏ¿©¶ó.
SELECT * FROM PROFESSOR;
SELECT
    PROFNO,
    HIREDATE,
    TO_CHAR(HIREDATE, 'YYYY/MM/DD HH24:MI:SS') R1,
    TO_CHAR(ROUND(HIREDATE, 'HH24'), 'YYYY/MM/DD HH24:MI:SS') R2,
    TO_CHAR(ROUND(HIREDATE, 'DD'), 'YYYY/MM/DD HH24:MI:SS') R3,
    TO_CHAR(ROUND(HIREDATE, 'MM'), 'YYYY/MM/DD HH24:MI:SS')R4, 
    TO_CHAR(ROUND(HIREDATE, 'YY'), 'YYYY/MM/DD HH24:MI:SS')R5
FROM PROFESSOR
WHERE DEPTNO = 101;

SELECT '22-02-02' -1 FROM DUAL;

INSERT INTO STUDENT(NAME, BIRTHDATE) VALUES ('½Å»ý¾Æ', SYSDATE);
INSERT INTO STUDENT(NAME, BIRTHDATE) VALUES ('½Å»ý¾Æ2', '22/02/02');
INSERT INTO STUDENT(NAME, BIRTHDATE) VALUES ('½Å»ý¾Æ3', '22-02-02');

SELECT * FROM STUDENT;

SELECT BIRTHDATE, SUBSTR(BIRTHDATE, 1, 2) FROM STUDENT;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­ †ÀÎÇÏÇÐ»ýÀÇÇÐ¹ø°ú»ý³â¿ùÀÏÁß¿¡¼­³â¿ù¢­t·ÂÇÏ¿©¶ó
SELECT STUDNO, NAME, TO_CHAR(BIRTHDATE, 'YYYY/MM')
FROM STUDENT;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­102¹øÇÐ°úÇÐ»ýÀÇÀÌ¸§, ÇÐ³â, »ý³â¿ùÀÏ(¹Ì±¹¼ø¼­ : ¿äÀÏ ¿ùÀÏ³â)À»­t·ÂÇÏ¿©¶ó
SELECT 
    NAME, GRADE, BIRTHDATE,
    TO_CHAR(BIRTHDATE, 'DAY MONTH DD YYYY P.M. "MISS"')
FROM STUDENT
WHERE DEPTNO = 102;

-- ±³¼öÅ×ÀÌºí¿¡¼­101¹øÇÐ°ú±³¼öµéÀÇÀÌ¸§, Á÷±Þ, ÀÔ»çÀÏ(¹Ì±¹ ½ºÅ¸ÀÏ : ¿ù ÀÏ(¼­¼ö) ³â)À»­t·ÂÇÏ¿©¶ó
SELECT NAME, POSITION, HIREDATE, LOWER(TO_CHAR(HIREDATE, 'MON DDTH YYYY DDSPTH'))
FROM PROFESSOR;

--º¸Á÷¼ö´çÀ»¹Þ´Â±³¼öµéÀÇÀÌ¸§, ±Þ¿©, º¸Á÷¼ö´ç, ±×¸®°í±Þ¿©¿Íº¸Á÷¼ö´çÀ»´õÀ™°ª¿¡12¸¦°öÀ™°á°ú¸¦¿¬ºÀÀ¸·Î­t·ÂÇÏ¿©¶ó.
SELECT NAME, SAL, COMM, TO_CHAR((SAL + COMM) * 12, '9,999')
FROM PROFESSOR
WHERE COMM IS NOT NULL;

SELECT '1,234,567,890' + 1 FROM DUAL;
SELECT TO_NUMBER('1,234,567,890', '9,999,999,999') + 1 FROM DUAL;
SELECT TO_CHAR(TO_NUMBER('1,234,567,890', '9,999,999,999') + 1,'9,999,999,999') FROM DUAL;

-- ÁÖ¹Îµî·Ï¹øÈ£¿¡¼­»ý³â¿ùÀÏÀ»Ãß­tÇÏ¿©?YY/MM/DD?ÇüÅÂ·Î­t·ÂÇÏ¿©¶ó.
SELECT * FROM STUDENT;
DESC STUDENT;
SELECT 
    IDNUM,
    SUBSTR(IDNUM, 1, 6),
    TO_DATE(SUBSTR(IDNUM, 1, 6), 'YYMMDD'),
    TO_CHAR(TO_DATE(SUBSTR(IDNUM, 1, 6), 'YYMMDD'), 'YY/MM/DD')
FROM STUDENT;

-- NVL(P1, P2) : P1 NULLÀÇ °¡´É¼ºÀÌ ÀÖ´Â °ª P2 : NULLÀÏ °æ¿ì ´ëÃ¼°ª
-- 201¹øÇÐ°ú±³¼öÀÇÀÌ¸§, Á÷±Þ, ±Þ¿©, º¸Á÷¼ö´ç, ±Þ¿©¿Íº¸Á÷¼ö´çÀÇÇÕ°è¸¦­t·ÂÇÏ¿©¶ó.
-- ´Ü, º¸Á÷¼ö´çÀÌNULLÀÎ°æ¿ì¿¡´Âº¸Á÷¼ö´çÀ»0À¸·Î°è»êÀ™´Ù.
SELECT * FROM PROFESSOR;
DESC PROFESSOR;
SELECT 
    NAME, POSITION, SAL, COMM, SAL+COMM,
    NVL(SAL+COMM, SAL),
    SAL+NVL(COMM, 0)
FROM PROFESSOR;
--WHERE DEPTNO = 201;

-- NVL2(P1, P2, P3) P1:NULLÀÇ °¡´É¼º °ª, P2:NULLÀÌ ¾Æ´Ò¶§ °ª, P3:³ÎÀÏ ¶§ °ª
SELECT 
    NAME, POSITION, SAL, COMM, SAL+COMM,
    NVL(SAL+COMM, SAL),
    NVL2(COMM, SAL+COMM, SAL)
FROM PROFESSOR;

SELECT 
    COALESCE(NULL, 1, 2),
    NVL(NVL(NULL, 1),2)
FROM DUAL;

-- ±³¼öÅ×ÀÌºí¿¡¼­±³¼öÀÇ¼Ò¼ÓÇÐ°ú¹øÈ£¸¦ÇÐ°úÀÌ¸§À¸·Îº¯ÃQÇÏ¿©­t·ÂÇÏ¿©¶ó. ÇÐ°ú¹øÈ£°¡101ÀÌ¸é?ÄÄÇ»ÅÍ°øÇÐ°ú?, 102ÀÌ¸é
-- ?¸ÖÆ¼¹Ìµð¾îÇÐ°ú?, 201ÀÌ¸é? †ÀÚ°øÇÐ°ú?, ³ª¸ÓÁöÇÐ°ú¹øÈ£´Â?±â°è°øÇÐ°ú?(default)·Îº¯ÃQÀ™´Ù.
SELECT * FROM PROFESSOR;
SELECT
    NAME, DEPTNO,
    DECODE(DEPTNO, 101, 'ÄÄÇ»ÅÍ°øÇÐ°ú',
            102, '¸ÖÆ¼¹Ìµð¾îÇÐ°ú',
            201, 'ÀüÀÚ°øÇÐ°ú',
             '±â°è°øÇÐ°ú') RESULT
FROM PROFESSOR;

-- ÇÐ»ýµéÀÇ ÅÂ¾î³­ ´Þ¿¡ µû¶ó °èÁ¤¸£ Ãâ·Â 3~5º½, 6~8¿©¸§
SELECT * FROM STUDENT;
DESC STUDENT;
SELECT NAME,
    BIRTHDATE,
    TO_CHAR(BIRTHDATE, 'MM'), 
    TRUNC(TO_CHAR(BIRTHDATE, 'MM') / 3),
--    DECODE(TO_CHAR(BIRTHDATE, 'MM'),
--            12 ,'°Ü¿ï',
--            1 ,'°Ü¿ï',
--            2 ,'°Ü¿ï'
    TO_CHAR(ADD_MONTHS(BIRTHDATE, -2),'Q'),
    DECODE(ADD_MONTHS(BIRTHDATE, -2),'Q'),
        1, 'º½',
        2, '¿©¸§',
        3, '°¡À»',
        '°Ü¿ï' SEASON2,
    DECODE(TRUNC(TO_CHAR(BIRTHDATE, 'MM') / 3),
        1, 'º½',
        2, '¿©¸§',
        3, '°¡À»',
        '°Ü¿ï') SEASON
FROM STUDENT;