SELECT 1234.567, ROUND(1234.567) FROM DUAL;

CREATE OR REPLACE FUNCTION MY_MOD (NUM1 NUMBER, NUM2 NUMBER) RETURN NUMBER IS
VN_REMAINDER NUMBER := 0;
VN_QUOTIENT NUMBER := 0;
BEGIN
    VN_QUOTIENT := FLOOR(NUM1 / NUM2);
    VN_REMAINDER := NUM1 - (NUM2 * VN_QUOTIENT);
    RETURN VN_REMAINDER;
END;
/

SELECT MOD(5, 2), MY_MOD(5, 2) FROM DUAL;

-- 함수 선언
-- 함수명 : GETDATE
-- 매개변수 X
-- 반환값은 현재시간 -7
-- 반환타입은 DATE
CREATE OR REPLACE FUNCTION GETDATE RETURN DATE IS
    
BEGIN
    RETURN SYSDATE-7;
END;
/

SELECT SYSDATE, GETDATE FROM DUAL;