SELECT S.DEPTNO, S.NAME, GRADE, STUDNO, PROFNO, P.NAME, POSITION
FROM STUDENT S
FULL JOIN PROFESSOR P USING(PROFNO);

SELECT * 
FROM PROFESSOR
WHERE POSITION = '背荐';

-- 荤侩磊酒捞叼啊?jun123?牢切积苞鞍篮切斥牢切积狼切锅, 捞抚, 切斥阑璽仿窍咯扼窜老青厚背楷魂磊
SELECT STUDNO, NAME, GRADE
FROM STUDENT
WHERE GRADE =
(SELECT GRADE
FROM STUDENT
WHERE USERID = 'jun123');

-- 101锅切苞切积甸狼乞闭个公霸焊促个公霸啊利篮切积狼捞抚, 切苞锅龋, 个公霸甫 免仿窍咯扼
SELECT NAME, DEPTNO, WEIGHT
FROM STUDENT
WHERE WEIGHT <
(SELECT AVG(WEIGHT)
FROM STUDENT
WHERE DEPTNO = 101);

-- 20101锅切积苞切斥捞鞍绊, 虐绰20101锅切积焊促奴切积狼捞抚, 切斥, 虐甫 免仿窍咯扼
SELECT GRADE
FROM STUDENT
WHERE STUDNO = 20101;

SELECT HEIGHT
FROM STUDENT
WHERE STUDNO = 20101;

SELECT NAME, GRADE, HEIGHT
FROM STUDENT
WHERE 
    GRADE = (
        SELECT GRADE
        FROM STUDENT
        WHERE STUDNO = 20101
        )
AND 
    HEIGHT > (
        SELECT HEIGHT
        FROM STUDENT
        WHERE STUDNO = 20101
        );
        
SELECT * FROM DEPARTMENT
WHERE COLLEGE = 100;

-- 沥焊固叼绢切何(何辑锅龋:100)俊家加等葛电切积狼切锅, 捞抚, 切苞锅龋甫璽仿窍咯扼
SELECT DEPTNO
FROM DEPARTMENT
WHERE COLLEGE = (
    SELECT DEPTNO
    FROM DEPARTMENT
    WHERE DNAME = '沥焊固叼绢切何'
);

SELECT STUDNO, NAME, DEPTNO
FROM STUDENT
WHERE DEPTNO IN(
    SELECT DEPTNO
    FROM DEPARTMENT
    WHERE COLLEGE = (
        SELECT DEPTNO
        FROM DEPARTMENT
        WHERE DNAME = '沥焊固叼绢切何'
    )
);

-- 葛电切积吝俊辑 4切斥 切积吝俊辑 虐啊力老累篮切积焊促虐啊奴切积狼切锅, 捞抚, 虐甫璽仿窍咯扼

SELECT STUDNO, NAME, HEIGHT
FROM STUDENT
WHERE HEIGHT > ANY(
    SELECT HEIGHT 
    FROM STUDENT
    WHERE GRADE = 4);


SELECT STUDNO, NAME, HEIGHT
FROM STUDENT
WHERE HEIGHT > (
SELECT MIN(HEIGHT)
FROM STUDENT
WHERE GRADE = 4);


-- 葛电切积吝俊辑4切斥切积吝俊辑虐啊力老 奴 切积焊促虐啊奴切积狼切锅, 捞抚, 虐甫璽仿窍咯扼
SELECT STUDNO, NAME, HEIGHT
FROM STUDENT
WHERE HEIGHT > ALL(
    SELECT HEIGHT 
    FROM STUDENT
    WHERE GRADE = 4
    );

SELECT STUDNO, NAME, HEIGHT
FROM STUDENT
WHERE HEIGHT > (
SELECT MAX(HEIGHT)
FROM STUDENT
WHERE GRADE = 4);

-- 葛电切积吝俊辑4切斥切积吝俊辑虐啊力老 奴切积焊促 虐啊 累篮 切积狼切锅, 捞抚, 虐甫璽仿窍咯扼
SELECT STUDNO, NAME, HEIGHT
FROM STUDENT
WHERE HEIGHT < ANY (
    SELECT HEIGHT 
    FROM STUDENT
    WHERE GRADE = 4);
    
SELECT STUDNO, NAME, HEIGHT
FROM STUDENT
WHERE HEIGHT < (
    SELECT MAX(HEIGHT)
    FROM STUDENT
    WHERE GRADE = 4);
    
-- 焊流荐寸阑罐绰背荐啊罊疙捞扼档乐栏搁葛电背荐狼背荐锅龋, 捞抚, 焊流荐寸弊府绊鞭咯客焊流荐寸狼钦阑璽仿窍咯扼
SELECT PROFNO, NAME, COMM, SAL+COMM
FROM PROFESSOR
WHERE EXISTS
(SELECT *
FROM PROFESSOR
WHERE COMM IS NOT NULL);

-- PAIRWISE 厚背规过俊狼秦切斥喊肺个公霸啊弥家牢切积狼捞抚, 切斥, 个公霸甫璽仿窍咯扼.
SELECT NAME, GRADE, WEIGHT
FROM STUDENT
WHERE (GRADE, WEIGHT) IN (
SELECT GRADE, MIN(WEIGHT)
FROM STUDENT
GROUP BY GRADE);

-- UNPAIRWISE 厚背规过俊狼秦切斥喊肺个公霸啊弥家牢切积狼捞抚, 切斥, 个公霸甫璽仿窍咯扼.

SELECT NAME, GRADE, WEIGHT
FROM STUDENT
WHERE GRADE IN(
    SELECT GRADE
    FROM STUDENT
    GROUP BY GRADE)
AND WEIGHT IN(
    SELECT MIN(WEIGHT)
    FROM STUDENT
    GROUP BY GRADE
)
ORDER BY 2;

-- 阿 切苞切积狼 乞闭虐焊促 虐啊 奴 切积狼捞抚, 切苞锅龋, 虐甫 免仿窍咯扼
SELECT DEPTNO, AVG(HEIGHT)
FROM STUDENT
GROUP BY DEPTNO;

SELECT STUDNO, NAME, DEPTNO, HEIGHT
FROM STUDENT S1
WHERE HEIGHT > (
    SELECT AVG(HEIGHT)
    FROM STUDENT S2
    WHERE S1.DEPTNO = S2.DEPTNO
GROUP BY DEPTNO);

-- 切锅, 捞抚, 切苞锅龋, 切苞捞抚阑 炼牢, 辑宏孽府
-- 炼牢
SELECT STUDNO, NAME, DEPTNO, DNAME
FROM STUDENT
JOIN DEPARTMENT USING(DEPTNO);

-- 辑宏孽府
SELECT STUDNO, NAME, S.DEPTNO, (SELECT DNAME FROM DEPARTMENT D WHERE D.DEPTNO = S.DEPTNO) DNAME
FROM STUDENT S;

SELECT STUDNO, NAME, PROFNO, (SELECT NAME FROM PROFESSOR P WHERE P.PROFNO = S.PROFNO) PNAME
, (SELECT DNAME FROM DEPARTMENT D WHERE D.DEPTNO = S.DEPTNO) DNAME
FROM STUDENT S;


-- DDL, DML, DCL
-- D绰 DATA, L篮 LANGUAGE
-- DDL : DATA DEFINITION LANGUAGE 单捞磐 沥狼绢
-- CREATE, ALTER, DROP, TRUNCATE, REPLACE, ... (抛捞喉甫 父甸锭)

-- DML : DATA MANUFACTIUAL LANGUAGE 抛捞磐 炼累绢
-- INSERT, UPDATE, DELETE, MERGE, ...(抛捞喉 郴狼 炼累绢)

-- DCL : DATA CONTROL LANGUAGE 抛捞磐 力绢绢
-- COMMIT, ROLLBACK, SAVEPOINT, GRANT, REVOKE, ... (扁鸥 殿殿...)
-- >> TCL 

INSERT INTO STUDENT
VALUES (10110, '全辨悼', 'hong', '1',
'8501011143098', '85/01/01', '041)630-3114',
170, 70, 101, 9903);

SELECT * FROM STUDENT;

ROLLBACK;

COMMIT;
