SELECT ROWNUM, EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE ROWNUM <= 20
AND ROWNUM > 10;

-- SUB QUERY를 활용한 페이지

-- 3페이지 보기 5개씩
SELECT RN, ID, RN LN
FROM (
SELECT ROWNUM RN, EMPLOYEE_ID ID, FIRST_NAME FN, LAST_NAME LN
FROM EMPLOYEES
WHERE ROWNUM <= 3 * 5
)
WHERE RN > (3 - 1) * 5;


