SELECT * FROM USER_TABLES;

SELECT * FROM ALL_TABLES;

SELECT * FROM DBA_TABLES; -- °ü¸®ÀÚ±ÇÇÑÀÌ ÀÖ´Â¸é º¼ ¼ö ÀÖÀ½

SELECT * FROM USER_SEQUENCES;

SELECT * FROM USER_VIEWS; -- ¾ÆÁ÷ ¸¸µç°Ô ¾ø¾î¼­ ¾Æ¹«°Íµµ ¾È³ª¿È

SELECT * FROM USER_INDEXES;

SELECT * FROM USER_CONSTRAINTS;

DESCRIBE STUDENT;

SELECT * FROM DICTIONARY;

SELECT TABLE_NAME FROM DICTIONARY WHERE TABLE_NAME LIKE 'USER%'; 

SELECT 'SELECT ' || column_name || ' FROM TBL_BOARD;' FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_BOARD';-- Å×ÀÌºí ±î¸ÔÀ» ¶§ ÇÑ¹ø¿¡ Ã£±â ÆíÇÔ

SELECT BNO FROM TBL_BOARD;
SELECT TITLE FROM TBL_BOARD;
SELECT CONTENT FROM TBL_BOARD;
SELECT HITCOUNT FROM TBL_BOARD;
SELECT REGDATE FROM TBL_BOARD;
SELECT WRITER FROM TBL_BOARD;


-- MEMBERÈ¸¿ø
-- Ä£±¸ µî·Ï
-- REQUESTER(¿äÃ»ÀÚ), RESPNSER(ÀÀ´äÀÚ) ÀÌ µÎ°³¸¦ ¹­¾î¼­ °íÀ¯Å°·Î ¸¸µé¾î¾ßÇÔ
-- ID1                ID2 ¿äÃ» »óÅÂ
-- ID2                ID1 ½ÂÀÎ »óÅÂ
-- ID1                ID4
-- ID1                ID3
-- ID3                ID1

-- ÂÊÁö ¹ß¼Û
-- SENDER(¹Þ´Â»ç¶÷), RECEIVER(º¸³½»ç¶÷), CONTENT(³»¿ë), REGDATE, RECEIVERDATE

SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;

CREATE TABLE SUBJECT (
    SUBNO NUMBER(5) CONSTRAINT PK_SUBJECT
    PRIMARY KEY DEFERRABLE INITIALLY DEFERRED,
--    USING INDEX TABLESPACE INDX,
    SUBNAME VARCHAR2(20)
    CONSTRAINT NN_SUBNAME NOT NULL,
    TERM VARCHAR2(1)
    CONSTRAINT CK_TERM CHECK (TERM IN ('1', '2')),
    TYPE VARCHAR2(1)
);

SELECT * FROM SUBJECT;

ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STUDNO);

CREATE TABLE SUGANG (
    STUDNO CONSTRAINT FK_SUGANG_STUDNO REFERENCES STUDENT(STUDNO),
    SUBNO CONSTRAINT FK_SUGANG_SUBNO REFERENCES SUBJECT(SUBNO),
    REGDATE DATE DEFAULT SYSDATE,
    RESULT NUMBER(3),
    CONSTRAINT PK_SUGANG PRIMARY KEY(STUDNO, SUBNO)
);
SELECT * FROM SUGANG;

-- ÇÐ»ýÅ×ÀÌºíÀÎ½ºÅÏ½º¸¦ÂüÁ¶ÇÏ¿©studno¿¡±âº»Å°, idnum¿¡°íÀ¯Å°,name¿¡NOT NULL ¹«°á¼ºÁ¦¾àÁ¶°ÇÀ»Ãß°¡ÇÏ¿©¶ó.
ALTER TABLE STUDENT ADD CONSTRAINT UK_IDNUM UNIQUE(IDNUM);
ALTER TABLE STUDENT ADD CONSTRAINT UK_IDNUM UNIQUE(USERID);
ALTER TABLE STUDENT MODIFY (NAME CONSTRAINT STUD_NAME_NN NOT NULL);

-- ÇÐ°úÅ×ÀÌºí¿¡ PK
ALTER TABLE DEPARTMENT MODIFY(DEPTNO CONSTRAINT PK_DEPARTMENT PRIMARY KEY);
-- DEPTNO ¿Ü·¡Å° Ãß°¡
ALTER TABLE STUDENT MODIFY(DEPTNO CONSTRAINT FK_DEPTNO REFERENCES DEPARTMENT(DEPTNO));


-- ÇÐ°ú Å×ÀÌºí¿¡ COLLEGE¿¡ FKÃß°¡ FK_COLLEGE
ALTER TABLE DEPARTMENT MODIFY(COLLEGE CONSTRAINT FK_COLLEGE REFERENCES DEPARTMENT(DEPTNO));

-- ÇÐ°ú Å×ÀÌºí¿¡ DNAME NN Ãß°¡ NN_DNAME
ALTER TABLE DEPARTMENT MODIFY (DNAME CONSTRAINT NN_DNAME NOT NULL);


-- ±³¼ö Å×ÀÌºí¿¡ PROFNO PK Ãß°¡ PK_PROFESSOR
ALTER TABLE PROFESSOR MODIFY(PROFNO CONSTRAINT PK_PROFESSOR PRIMARY KEY);

-- ±³¼ö Å×ÀÌºí¿¡ NAME NN Ãß°¡
ALTER TABLE PROFESSOR MODIFY(NAME CONSTRAINT NN_PROF_NAME NOT NULL);

-- ±³¼ö Å×ÀÌºí¿¡ DEPTNO FK Ãß°¡
ALTER TABLE PROFESSOR MODIFY(DEPTNO CONSTRAINT FK_PROF_DEPTNO REFERENCES DEPARTMENT(DEPTNO));


-- ÇÐ»ý Å×ÀÌºí¿¡ PROFNO FK Ãß°¡
ALTER TABLE STUDENT MODIFY(PROFNO CONSTRAINT FK_STUD_PROFNO REFERENCES PROFESSOR(PROFNO));

-- ÇÐ»ý Å×ÀÌºí¿¡ GRADE CK Ãß°¡(1~4)
ALTER TABLE STUDENT MODIFY(GRADE CONSTRAINT CK_GRADE CHECK(GRADE BETWEEN '1' AND '4'));



SELECT * FROM USER_CONSTRAINTS;

INSERT INTO SUBJECT VALUES (1001, 'ÀÚ¹Ù', '1', NULL);
INSERT INTO SUBJECT VALUES (1002, '¿À¶óÅ¬', '2', NULL);
SELECT * FROM SUBJECT;
-- Áö¿¬ »óÅÂ¿¡¼­´Â Áßº¹°ª(EX >> 1001)ÀÌ µé¾î°¥ ¼ö ÀÖ¾î¼­ Á¶È¸´Â °¡´ÉÇÏÁö¸¸ COMMIT½Ã  ·Ñ¹éÀÌµÊ
COMMIT;

SELECT * FROM USER_CONS_COLUMNS;
SELECT * FROM USER_CONSTRAINTS;


-- ºÎ¼­Å×ÀÌºí¿¡¼­name Ä®·³À»°íÀ¯ÀÎµ¦½º·Î»ý¼ºÇÏ¿©¶ó.
-- ´Ü, °íÀ¯ÀÎµ¦½ºÀÇÀÌ¸§À»idx_dept_nameÀ¸·ÎÁ¤ÀÇÇÑ´Ù

CREATE UNIQUE INDEX IDX_DEPT_NAME ON DEPARTMENT(DNAME);

SELECT * FROM USER_INDEXES;

-- ±âº»Å° »ý¼º : ÇØ´ç ÄÃ·³À¸·Î NN,UK, UNIQUE INDEX Ãß°¡

SELECT /* + INDEX(D PK_DEPARTMENT) */ * FROM DEPARTMENT D;

DESC TBL_BOARD;

-- PK_BOARD ±âº»Å°¸¦ Ãß°¡ BNO
ALTER TABLE TBL_BOARD MODIFY(BNO CONSTRAINT PK_BOARD PRIMARY KEY);
ALTER TABLE TBL_BOARD DROP CONSTRAINT PK_BOARD;

-- ±âº»Å°°¡ ¾øÀ¸¸é ÄÚ½ºÆ®°¡ ¾öÃ»³ª°Ô ³ô¾ÆÁü
SELECT * FROM (
SELECT A.*, ROWNUM RN FROM (
    SELECT B.* FROM TBL_BOARD B ORDER BY BNO DESC
    ) A WHERE ROWNUM <= 30
)
WHERE RN > 20;

-- ÀÎµ¦½º ÈùÆ® »ç¿ë ½Ã, ÄÚ½ºÆ®µµ ³·°í ÄÚµå ¼öµµ ÁÙ°í ±»±»
SELECT * FROM (
    SELECT /*+ INDEX_DESC(A PK_BOARD) */ A.*, ROWNUM RN FROM TBL_BOARD A WHERE ROWNUM <= 30
)
WHERE RN > 20;

-- ÇÐ»ýÅ×ÀÌºíÀÇbirthdate Ä®·³À»ºñ°íÀ¯ÀÎµ¦½º·Î»ý¼ºÇÏ¿©¶ó.
-- ºñ°íÀ¯ÀÎµ¦½ºÀÇÀÌ¸§Àºidx_stud_birthdate·ÎÁ¤ÀÇÇÑ´Ù

CREATE INDEX IDX_STUD_BIRTHDATE ON STUDENT(BIRTHDATE);
SELECT * FROM STUDENT WHERE BIRTHDATE = '79/07/02';

-- ÇÐ»ýÅ×ÀÌºíÀÇdeptno, grade Ä®·³À»°áÇÕÀÎµ¦½º·Î»ý¼ºÇÏ¿©¶ó.
-- °áÇÕÀÎµ¦½ºÀÇÀÌ¸§Àºidx_stud_dno_grade ·ÎÁ¤ÀÇÇÑ´Ù
DROP INDEX IDX_STUD_DNO_GRADE;
CREATE INDEX IDX_STUD_DNO_GRADE ON STUDENT(DEPTNO, TO_CHAR(GRADE));
SELECT * FROM STUDENT WHERE DEPTNO = 101 AND GRADE = 4;

-- ÇÐ»ýÅ×ÀÌºíÀÇdeptno¿Íname Ä®·³À¸·Î°áÇÕÀÎµ¦½º¸¦»ý¼ºÇÏ¿©¶ó.
-- ´Ü, deptno Ä®·³À»³»¸²Â÷¼øÀ¸·Îname Ä®·³Àº¿À¸§Â÷¼øÀ¸·Î»ý¼ºÇÏ¿©¶ó
CREATE INDEX IDX_STUD_DNO_NAME ON STUDENT(DEPTNO DESC, NAME);
SELECT * FROM STUDENT WHERE DEPTNO > 0 AND NAME > '°¡'; -- Á¦´ë·Î ¾ÈÅ»°æ¿ì¿¡´Â ÈùÆ®·Î!!

SELECT /*+ INDEX_DESC(STUDENT IDX_STUD_DNO_NAME)*/ * FROM STUDENT;

SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;

SELECT *
FROM USER_INDEXES
JOIN USER_IND_COLUMNS USING(INDEX_NAME);

SELECT * FROM DICT WHERE TABLE_NAME LIKE 'USER%IND%';
SELECT * FROM USER_OBJECTS;

-- ÇÐ¹ø, ÀÌ¸§, ÇÐ°ü¹øÈ£, ±³¼ö¹øÈ£¸¦ °¡Áö´Â STUD_TMP¶ó´Â Å×ÀÌºíÀ» »ý¼ºÇÏ¿©¶ó
DROP TABLE STUD_TMP;
CREATE TABLE STUD_TMP AS
SELECT STUDNO, NAME, DEPTNO, PROFNO
FROM STUDENT;

-- ÇÐ¹ø, ÀÌ¸§, ÇÐ°ü¹øÈ£, ±³¼ö¹øÈ£¸¦ °¡Áö´Â STUD_TMP¶ó´Â ºä¸¦ »ý¼ºÇÏ¿©¶ó
DROP VIEW STUD_TMP;
CREATE VIEW STUD_TMP AS
SELECT STUDNO, NAME, DEPTNO, PROFNO
FROM STUDENT;

INSERT INTO STUD_TMP VALUES(12345, '±è±è±è', 101, NULL);
INSERT INTO STUD_TMP VALUES(12346, '±è±è±è', NULL, NULL);
-- INSERT INTO STUD_TMP VALUES(NULL, '±è±è±è', 101, NULL); ÇÐ¹ø¿¡ NULLÀÌ µé¾î°¥ ¼ö ¾øÀ½
--INSERT INTO STUD_TMP VALUES(10101, '±è±è±è', 101, NULL); Áßº¹°ªµµ µé¾î°¥ ¼ö ¾øÀ½

SELECT * FROM STUDENT;
SELECT * FROM STUD_TMP;

SELECT * FROM USER_VIEWS;


CREATE OR REPLACE VIEW STUD_TMP AS
SELECT STUDNO, NAME, DEPTNO, PROFNO
FROM STUDENT;

SELECT * FROM HR.EMPLOYEES;
SELECT * FROM HR.EMPLOYEES A JOIN DEPARTMENT B ON A.EMPLOYEE_ID = B.DEPTNO;

-- ÇÐ»ýÅ×ÀÌºí°úºÎ¼­Å×ÀÌºíÀ»Á¶ÀÎÇÏ¿©102¹øÇÐ°úÇÐ»ýµéÀÇÇÐ¹ø, ÀÌ¸§, ÇÐ³â, ÇÐ°úÀÌ¸§À¸·ÎÁ¤ÀÇµÇ´Âº¹ÇÕºä¸¦»ý¼ºÇÏ¿©¶ó.
CREATE OR REPLACE VIEW VIEW_COMP_TEST AS
SELECT STUDNO, NAME, GRADE, DNAME FROM STUDENT
NATURAL JOIN DEPARTMENT;

SELECT * FROM VIEW_COMP_TEST;

INSERT INTO VIEW_COMP_TEST VALUES(12346, 'ÀÌÀÌÀÌ', '3', 'ÄÄÇ»ÅÍ°øÇÐ°ú'); 
-- º¹ÇÕºä´Â INSERT¸¦ ÇÒ ¼ö ¾øÀ½
DELETE FROM VIEW_COMP_TEST WHERE DNAME IS NULL;
SELECT * FROM STUDENT;

-- ÇÐ»ýÀÇ Åº»ý¿¬µµº° ÀÎ¿ø¼ö¸¦ ±¸ÇÏ¿©¶ó. ±×¸®°í ÀÌ µ¥ÀÌÅÍ¸¦ »ç¿ëÇØ VIEW_COMP_TEST2¶ó´Â VIEW¸¦ »ý¼ºÇÏ¿©¶ó.
SELECT BIRTHDATE, SUBSTR(BIRTHDATE, 1,2) FROM STUDENT;

SELECT COUNT(SUBSTR(BIRTHDATE, 1,2)) FROM STUDENT
GROUP BY SUBSTR(BIRTHDATE, 1,2);

CREATE OR REPLACE VIEW VIEW_COMP_TEST2 AS
SELECT COUNT(SUBSTR(BIRTHDATE, 1,2)) FROM STUDENT
GROUP BY SUBSTR(BIRTHDATE, 1,2); -- VIEW¿¡¼­ ½ÇÆÐ¾Ö...
-- »ê¼ú °°Àº°Ô µé¾î°¡¸é º°ÄªÀ» Áà¾ßÇÔ!!! 

CREATE OR REPLACE VIEW VIEW_COMP_TEST2 AS
SELECT TO_CHAR(BIRTHDATE, 'YYYY') BIRTH, COUNT(*) CNT
FROM STUDENT 
GROUP BY TO_CHAR(BIRTHDATE, 'YYYY');

SELECT * FROM VIEW_COMP_TEST2;

DELETE VIEW_COMP_TEST2 WHERE BIRTH = 1980;

--ÀÎ¶óÀÎºä¸¦ »ç¿ëÇÏ¿© ÇÐ°úº°·Î ÇÐ»ýµéÀÇ Æò±ÕÅ°¿Í Æò±Õ¸ö¹«°Ô, ÇÐ°úÀÌ¸§À» ­t·ÂÇÏ¿©¶ó.
SELECT  DNAME, AVG(WEIGHT), AVG(HEIGHT) 
FROM (
    SELECT DEPTNO, AVG(WEIGHT), AVG(HEIGHT) 
    FROM STUDENT GROUP BY DEPTNO)
JOIN DEPARTMENT USING(DEPTNO); -- ÂS ½ÇÆÐ¾Ö...

SELECT AH, AW, DNAME 
FROM ( 
    SELECT DEPTNO, AVG(HEIGHT) AH, AVG(WEIGHT) AW
    FROM STUDENT
    GROUP BY DEPTNO
) NATURAL JOIN DEPARTMENT;
    
GRANT SELECT ON DEPARTMENT TO HR;

SELECT * FROM HR.EMPLOYEES;

CREATE SYNONYM EMPS FOR HR.EMPLOYEES;
SELECT * FROM EMPS;

-- »ç¿ë¿¹°èÃþÀûÁúÀÇ¹®À»»ç¿ëÇÏ¿©ºÎ¼­Å×ÀÌºí¿¡¼­ÇÐ°ú,ÇÐºÎ,´Ü°ú´ëÇÐÀ»°Ë»öÇÏ¿©´Ü´ë,
-- ÇÐºÎÇÐ°ú¼øÀ¸·Îtop-down Çü½ÄÀÇ°èÃþ±¸Á¶·ÎÃâ·ÂÇÏ¿©¶ó. ´Ü, ½ÃÀÛµ¥ÀÌÅÍ´Â10¹øºÎ¼­ÀÌ´Ù.
SELECT --DEPTNO, DNAME, COLLEGE, LEVEL
LPAD(' ', LEVEL * 2) || DNAME D
FROM DEPARTMENT
START WITH DEPTNO = 10
CONNECT BY PRIOR DEPTNO = COLLEGE;


-- »ç¿ë¿¹°èÃþÀûÁúÀÇ¹®À»»ç¿ëÇÏ¿©ºÎ¼­Å×ÀÌºí¿¡¼­ÇÐ°ú,ÇÐºÎ,´Ü°ú´ëÇÐÀ»°Ë»öÇÏ¿©ÇÐ°ú,
-- ÇÐºÎ´Ü´ë¼øÀ¸·Îbottom-up Çü½ÄÀÇ°èÃþ±¸Á¶·ÎÃâ·ÂÇÏ¿©¶ó. ´Ü, ½ÃÀÛµ¥ÀÌÅÍ´Â102¹øºÎ¼­ÀÌ´Ù
SELECT --DEPTNO, DNAME, COLLEGE, LEVEL
LPAD(' ', LEVEL * 2) || DNAME D
FROM DEPARTMENT
START WITH DEPTNO = 101
CONNECT BY PRIOR COLLEGE = DEPTNO;