-- ÇÐ»ý Åº»ý °èÀýº° ÀÎ¿ø ¼ö ±¸ÇÏ±â
SELECT * FROM STUDENT;
SELECT STUDNO, NAME, BIRTHDATE, TO_CHAR(BIRTHDATE, 'MM'),
    CASE 
        WHEN TO_CHAR(BIRTHDATE, 'MM') IN(3, 4, 5) THEN 'º½'
        WHEN TO_CHAR(BIRTHDATE, 'MM') IN(6, 7, 8) THEN '¿©¸§'
        WHEN TO_CHAR(BIRTHDATE, 'MM') IN(9, 10, 11) THEN '°¡À»'
        ELSE '°Ü¿ï'
    END
FROM STUDENT;   -- ¸øÇßÀ½....

SELECT STUDNO, NAME, BIRTHDATE, ADD_MONTHS(BIRTHDATE, -2), TO_CHAR(ADD_MONTHS(BIRTHDATE, -2), 'Q')
FROM STUDENT;

SELECT 
CASE
    WHEN TO_CHAR(ADD_MONTHS(BIRTHDATE, -2), 'Q') = 1 THEN 'º½'
    WHEN TO_CHAR(ADD_MONTHS(BIRTHDATE, -2), 'Q') = 2 THEN '¿©¸§'
    WHEN TO_CHAR(ADD_MONTHS(BIRTHDATE, -2), 'Q') = 3 THEN '°¡À»'
    ELSE '°Ü¿ï'
END SEASON,
COUNT(*)
FROM STUDENT
WHERE BIRTHDATE IS NOT NULL
GROUP BY TO_CHAR(ADD_MONTHS(BIRTHDATE, -2), 'Q')
ORDER BY TO_CHAR(ADD_MONTHS(BIRTHDATE, -2), 'Q');


SELECT STUDNO, NAME, S.DEPTNO, DNAME
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO = D.DEPTNO
AND STUDNO = 10101;

-- 10101ÇÐ»ýÀÇ ÇÐ¹ø, ÀÌ¸§, ÇÐ°ú¹øÈ£, ÇÐ°úÀÌ¸§, ´ã´ç±³¼ö¹øÈ£, ´ã´ç±³¼ö ÀÌ¸§
SELECT * FROM STUDENT;
SELECT * FROM DEPARTMENT;
SELECT * FROM PROFESSOR;

SELECT STUDNO, S.NAME, STUDNO, S.DEPTNO, S.PROFNO, P.NAME
FROM STUDENT S, DEPARTMENT D, PROFESSOR P
WHERE S.PROFNO = P.PROFNO 
AND STUDNO = 10101; -- ¶Ç ¸øÇÔ...¤Ð¤Ð¤Ð

SELECT STUDNO, S.NAME, S.DEPTNO, DNAME, S.PROFNO, P.NAME
FROM STUDENT S, DEPARTMENT D , PROFESSOR P
WHERE S.DEPTNO = D.DEPTNO
AND S.PROFNO = P.PROFNO
AND STUDNO = 10101;
-- ´Ù¸¥ ¹æ¹ýÀ¸·Î
SELECT STUDNO, S.NAME, S.DEPTNO, DNAME, PROFNO, P.NAME
FROM STUDENT S
JOIN DEPARTMENT D ON S.DEPTNO = D.DEPTNO
JOIN PROFESSOR P USING(PROFNO)
WHERE STUDNO = 10101;

SELECT * FROM STUDENT, DEPARTMENT;

SELECT * FROM STUDENT CROSS JOIN DEPARTMENT;

-- ÇÐ»ýÅ×ÀÌºí°úºÎ¼­Å×ÀÌºíÀ»EQUI JOINÇÏ¿© ÇÐ¹ø, ÀÌ¸§, ÇÐ°ú¹øÈ£, ¼Ò¼ÓÇÐ°úÀÌ¸§, ÇÐ°ú À§Ä¡¸¦ Ãâ·ÂÇÏ¿©¶ó
SELECT STUDNO, NAME, S.DEPTNO, DNAME, LOC
FROM STUDENT S, DEPARTMENT D
WHERE S.DEPTNO = D.DEPTNO;
-- NULLÀº ºñ±³¿¬»êÀ¸·Î ÇÏ¸é FALSEÃ³¸®µÈ´Ù
SELECT STUDNO, NAME, DEPTNO, DNAME, LOC
FROM STUDENT
JOIN DEPARTMENT USING(DEPTNO);

--NATURAL JOINÀ»ÀÌ¿ëÇÏ¿©±³¼ö¹øÈ£, ÀÌ¸§, ÇÐ°ú¹øÈ£, ÇÐ°úÀÌ¸§À»­t·ÂÇÏ¿©¶ó.
SELECT PROFNO, NAME, DEPTNO, DNAME
FROM PROFESSOR
NATURAL JOIN DEPARTMENT;

-- ±³¼öÅ×ÀÌºí°ú ±Þ¿©µî±ÞÅ×ÀÌºíÀ» NON-EQUI JOINÇÏ¿© ±³¼öº°·Î ±Þ¿©µî±ÞÀ» ­t·ÂÇÏ¿©¶ó.
SELECT * FROM SALGRADE;
SELECT NAME, SAL, GRADE 
FROM PROFESSOR
JOIN SALGRADE 
--ON SAL <= HISAL AND SAL >= LOSAL;
ON SAL BETWEEN LOSAL AND HISAL;

-- 4Çà 2¿­Â¥¸® ¼ýÀÚ°¡ ÀúÀåµÇ Å×ÀÌºí 2°³
CREATE TABLE J1 (
    A NUMBER,
    B NUMBER
);
CREATE TABLE J2 (
    A NUMBER,
    C NUMBER
);

INSERT INTO J1 VALUES (1, 1);
INSERT INTO J1 VALUES (2, 2);
INSERT INTO J1 VALUES (3, 3);
INSERT INTO J1 VALUES (4, 4);

INSERT INTO J2 VALUES (1, 5);
INSERT INTO J2 VALUES (2, 6);
INSERT INTO J2 VALUES (5, 6);
INSERT INTO J2 VALUES (NULL, 7);

SELECT * FROM J1 NATURAL JOIN J2;
SELECT * FROM J1 JOIN J2 ON J1.A != J2.A;

SELECT DISTINCT PROFNO 
FROM STUDENT 
WHERE PROFNO IS NOT NULL
ORDER BY 1;

DELETE STUDENT WHERE STUDNO = 30303 OR STUDNO IS NULL;

-- ÃÑ ÇÐ»ýÀº 16¸í , ´ã´ç±³¼ö°¡ ÀÖ´Â ÇÐ»ýÀº 10¸í ¾ø´Â ÇÐ»ýÀº 6¸í

-- Áöµµ ±³¼ö°¡ ¾ø´Â ÇÐ»ýµµ Ãâ·Â
SELECT STUDNO, S.NAME, PROFNO, P.NAME
FROM STUDENT S
LEFT JOIN PROFESSOR P USING(PROFNO);

-- ´ã´ç ÇÐ»ýÀÌ ¾ø´Â ±³¼ö
SELECT STUDNO, S.NAME, PROFNO, P.NAME
FROM STUDENT S
RIGHT JOIN PROFESSOR P USING(PROFNO);

-- Áöµµ ±³¼öµµ ¾ø°í ÇÐ»ýµµ ¾ø´Â ´Ù
SELECT STUDNO, S.NAME, PROFNO, P.NAME
FROM STUDENT S
FULL JOIN PROFESSOR P USING(PROFNO);

SELECT STUDNO, S.NAME, PROFNO, P.NAME
FROM STUDENT S
LEFT JOIN PROFESSOR P USING(PROFNO)
WHERE PROFNO IS NULL;

SELECT STUDNO, S.NAME, PROFNO, P.NAME
FROM STUDENT S
RIGHT JOIN PROFESSOR P USING(PROFNO)
WHERE STUDNO IS NULL;

SELECT STUDNO, S.NAME, PROFNO, P.NAME
FROM STUDENT S
FULL JOIN PROFESSOR P USING(PROFNO)
WHERE STUDNO IS NULL OR PROFNO IS NULL;


-- ÇÐ»ýÅ×ÀÌºí°ú±³¼öÅ×ÀÌºíÀ»Á¶ÀÎÇÏ¿©ÀÌ¸§, ÇÐ³â, Áöµµ±³¼öÀÇÀÌ¸§, Á÷±ÞÀ»­t·ÂÇÏ¿©¶ó. 
-- ´Ü, Áöµµ±³¼ö°¡¹èÁ¤µÇÁö¾ÊÀºÇÐ»ýÀÌ¸§µµÇÔ²²­t·ÂÇÏ¿©¶ó.
SELECT S.NAME, GRADE, P.NAME, POSITION
FROM STUDENT S , PROFESSOR P
WHERE S.PROFNO = P.PROFNO(+);


SELECT S.NAME, GRADE, P.NAME, POSITION
FROM STUDENT S , PROFESSOR P
WHERE S.PROFNO = P.PROFNO(+)
UNION ALL
SELECT S.NAME, GRADE, P.NAME, POSITION
FROM STUDENT S , PROFESSOR P
WHERE S.PROFNO(+) = P.PROFNO;


--SELECT D1.DEPTNO, D1.DNAME, D1.COLLEGE, D2.DEPTNO, D2.DNAME, D2.COLLEGE 
SELECT D1.DNAME || 'ÀÇ »óÀ§ÇÐ°ú´Â ' || NVL2(D2.DNAME, D2.DNAME || 'ÀÔ´Ï´Ù', '¾ø½À´Ï´Ù') AS RESULT 
FROM DEPARTMENT D1 LEFT JOIN DEPARTMENT D2 ON D1.COLLEGE = D2.DEPTNO;
--FROM DEPARTMENT D1, DEPARTMENT D2
--WHERE D1.COLLEGE = D2.DEPTNO (+);

--1. ±³¼öÅ×ÀÌºí¿¡¼­? †ÀºÁö?±³¼öÀÇÁ÷±Þ°Ë»öSQL ¸í·É’K½ÇÇà
--2. ±³¼öÅ×ÀÌºíÀÇÁ÷±ÞÄ®·³¿¡¼­1 ¿¡¼­¾òÀº°á°ú°ª°úµ¿ÀÏÀ™Á÷±ÞÀ»°¡£’±³¼ö°Ë»ö¸í·É’K½ÇÇà
SELECT * 
FROM PROFESSOR 
WHERE POSITION = (
    SELECT POSITION 
    FROM PROFESSOR 
    WHERE NAME = 'ÀüÀºÁö'
);

-- 1Çà 1¿­ÀÇ ´Ü ÇÏ³ªÀÇ °ªÀ» ¹ÝÈ¯ÇÏ´Â ¼­ºêÄõ¸® >> ½ºÄ®¶ó ¼­ºêÄõ¸®