-- ÇÐ»ýÅ×ÀÌºí¿¡¼­1ÇÐ³âÇÐ»ý¢°Ë»öÇÏ¿©ÇÐ¹ø, ÀÌ¸§, ÇÐ°ú¹øÈ£¸¦­t·ÂÇÏ¿©¶ó
SELECT * FROM STUDENT;
SELECT STUDNO, NAME, GRADE, DEPTNO FROM STUDENT;
SELECT STUDNO, NAME, DEPTNO FROM STUDENT
WHERE GRADE = '1';  
-- GRADE´Â ¹ÙÂ÷Å¸ÀÔ 1Àº ¼ýÀÚÀÎµ¥ ÀÚµ¿À¸·Î Çüº¯È¯ ÇØÁÜ, 
-- ÇÏÁö¸¸ Á¤È®ÇÏ°Ô ÇÏ´Â°Ô ÁÁÀ½

DESC STUDENT;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­¸ö¹«°Ô°¡70kg ÀÌÇÏÀÎÇÐ»ý¢°Ë»öÇÏ¿©ÇÐ¹ø, ÀÌ¸§, ÇÐ³â, ÇÐ°ú¹øÈ£, ¸ö¹«°Ô¸¦­t·ÂÇÏ¿©¶ó.
SELECT * FROM STUDENT;
SELECT STUDNO, NAME, GRADE, DEPTNO, WEIGHT FROM STUDENT
WHERE WEIGHT <= 70 ;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­1ÇÐ³âÀÌ¸é¼­¸ö¹«°Ô°¡70kg ÀÌ»óÀÎÇÐ»ý¢°Ë»öÇÏ¿©ÀÌ¸§, ÇÐ³â, ¸ö¹«°Ô, ÇÐ°ú¹øÈ£¸¦­t·ÂÇÏ¿©¶ó.
SELECT * FROM STUDENT;
SELECT NAME, GRADE, WEIGHT, DEPTNO FROM STUDENT;
SELECT NAME, GRADE, WEIGHT, DEPTNO FROM STUDENT 
WHERE GRADE = '1'
AND WEIGHT >= 70;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­1ÇÐ³âÀÌ°Å³ª¸ö¹«°Ô°¡70kg ÀÌ»óÀÎÇÐ»ý¢°Ë»öÇÏ¿©ÀÌ¸§, ÇÐ³â, ¸ö¹«°Ô, ÇÐ°ú¹øÈ£¸¦­t·ÂÇÏ¿©¶ó.
SELECT NAME, GRADE, WEIGHT, DEPTNO FROM STUDENT 
WHERE GRADE = '1'
OR WEIGHT >= 70;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­ÇÐ°ú¹øÈ£°¡?101?ÀÌ¾Æˆ‘ÇÐ»ýÀÇÇÐ¹ø°úÀÌ¸§°úÇÐ°ú¹øÈ£¸¦­t·ÂÇØ¶ó
SELECT DEPTNO FROM STUDENT
WHERE DEPTNO != 101;

-- BETWEEN ¿¬»êÀÚ¸¦»ç¿ëÇÏ¿©¸ö¹«°Ô°¡50kg¿¡¼­70kg »çÀÌÀÎÇÐ»ýÀÇÇÐ¹ø, ÀÌ¸§, ¸ö¹«°Ô¸¦­t·ÂÇÏ¿©¶ó.
SELECT * FROM STUDENT;
SELECT STUDNO, NAME, WEIGHT FROM STUDENT
WHERE WEIGHT BETWEEN 50 AND 70;

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­81³â¿¡¼­83³âµµ¿¡ÅÂ¾î³­ÇÐ»ýÀÇÀÌ¸§°ú»ý³â¿ùÀÏÀ»Ãâ·ÂÇØ¶ó
SELECT * FROM STUDENT;
SELECT BIRTHDATE, NAME FROM STUDENT
WHERE TO_CHAR(BIRTHDATE, 'YY') IN (81, 82, 83);
-- WHERE TO_CHAR(BIRTHDATE, 'YY') BETWEEN 81 AND 83;
-- WHERE BIRTHDATE BETWEEN '81/01/01' AND '83/12/31';

-- IN ¿¬»êÀÚ¸¦ »ç¿ëÇÏ¿© 102¹øÇÐ°ú¿Í 201¹øÇÐ°ú ÇÐ»ýÀÇÀÌ¸§, ÇÐ³â, ÇÐ°ú¹øÈ£¸¦ Ãâ·ÂÇÏ¿©¶ó
SELECT * FROM STUDENT;
SELECT NAME, GRADE, DEPTNO FROM STUDENT
WHERE DEPTNO NOT IN  ('102','201');

-- ÇÐ»ýÅ×ÀÌºí¿¡¼­¼ºÀÌ?±è?¾¾ÀÎÇÐ»ýÀÇÀÌ¸§, ÇÐ³â, ÇÐ°ú¹øÈ£¸¦­t·ÂÇÏ¿©¶ó.
SELECT * FROM STUDENT;
SELECT NAME, GRADE, DEPTNO FROM STUDENT
WHERE NAME LIKE '±è%';

-- ÀÌ¸§ Áß¿¡ 'µ¿'ÀÌ µé¾î°¡´Â ÇÐ»ýÀÇ ÇÐ¹ø, ÀÌ¸§ Á¶È¸
SELECT * FROM STUDENT;
SELECT STUDNO, NAME FROM STUDENT
WHERE NAME LIKE '%µ¿%';

INSERT INTO STUDENT(NAME) VALUES ('µ¿¼­³²');

SELECT * FROM PROFESSOR;
SELECT AVG(SAL) FROM PROFESSOR;
SELECT POSITION, AVG(SAL) FROM PROFESSOR GROUP BY POSITION;



