SELECT RN, BNO, TITLE, CONTENT FROM (
    SELECT
    /*+ INDEX_DESC(TBL_BOARD BOARD_PK) */
    ROWNUM RN, BNO, TITLE, CONTENT 
    FROM TBL_BOARD
    WHERE ROWNUM <= 3 * 10
)
WHERE RN > (3 - 1) * 10;

-- 현재 : 페이지번호가 존재하는 질의문, BNO 역순, 페이지번호, AMOUNT
-- 댓글페이징 : 페이지번호가 존재하지 않은 질의문, BNO 정순, 마지막글번호, AMOUNT

    SELECT
    /*+ INDEX(TBL_BOARD BOARD_PK) */
    ROWNUM RN, BNO, TITLE, CONTENT 
    FROM TBL_BOARD
    WHERE ROWNUM <= 10
    AND BNO > 42;




SELECT
/*+ INDEX_DESC() */
* FROM TBL_BOARD ORDER BY BNO + 1 DESC;

SELECT
/*+ FULL(T) */ T.*, ROWNUM
FROM TBL_BOARD T ORDER BY BNO DESC;


SELECT
/*+ FULL(TBL_BOARD) */
* FROM TBL_BOARD WHERE BNO = 1;

SELECT ROWNUM, BNO, TITLE FROM TBL_BOARD ORDER BY BNO DESC;


SELECT * FROM TBL_BOARD ORDER BY BNO + 1 DESC;

INSERT INTO TBL_BOARD (BNO, TITLE, CONTENT, WRITER)
SELECT SEQ_BOARD.NEXTVAL, TITLE, CONTENT, WRITER FROM TBL_BOARD;

ROLLBACK;


SELECT COUNT(*) FROM TBL_BOARD;