CREATE TABLE TBL_BOARD_ATTACH (
    UUID VARCHAR2(100) CONSTRAINT BOARD_ATTACH_PK PRIMARY KEY,
    PATH VARCHAR2(100),
    ORIGIN VARCHAR2(1000),
    IMAGE CHAR(1) DEFAULT '0',
    BNO REFERENCES TBL_BOARD(BNO)
);

CREATE TABLE TBL_REPLY_ATTACH (
    UUID VARCHAR2(100) CONSTRAINT REPLY_ATTACH_PK PRIMARY KEY,
    PATH VARCHAR2(100),
    ORIGIN VARCHAR2(1000),
    IMAGE CHAR(1) DEFAULT '0',
    RNO REFERENCES TBL_REPLY(RNO)
);

CREATE TABLE TBL_MEMBER_ATTACH (
    UUID VARCHAR2(100) CONSTRAINT MEMBER_ATTACH_PK PRIMARY KEY,
    PATH VARCHAR2(100),
    ORIGIN VARCHAR2(1000),
    IMAGE CHAR(1) DEFAULT '0',
    USERID REFERENCES TBL_MEMBER(USERID)
);