UPDATE TBL_MEMBER SET
PW =?,
NAME =?,
SI =?,
SGG =?,
EMD =?,
ROADADDR =?,
ADDRDETAIL =?,
ZIPNO =?,
ROADFULLADDR =?,
JIBUNADDR =?
WHERE ID = ?;

SELECT COLUMN_NAME FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_MEMBER' ORDER BY COLUMN_ID;

SELECT 'sb.append("' || COLUMN_NAME || ' =?,\n");'   FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_MEMBER' ORDER BY COLUMN_ID;

SELECT 'pstmt.setString(idx++, member.get' || INITCAP(COLUMN_NAME) || '();'   FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TBL_MEMBER' ORDER BY COLUMN_ID;

SELECT * FROM tbl_member;

SELECT * FROM tbl_board WHERE WRITER = 'aaaa';
UPDATE TBL_BOARD SET
WRITER = NULL
WHERE WRITER = 'aaaa';

SELECT * FROM tbl_REPLY WHERE WRITER = 'aaaa';



-- 프로시저 선언
-- 회원 탈퇴기능 수행
-- 프로시저이름 : QUIT_PROC
-- 매개변수 : P_ID / NUMBER.ID 타입
CREATE OR REPLACE PROCEDURE QUIT_PROC(P_ID TBL_MEMBER.ID%TYPE) IS
BEGIN
    UPDATE TBL_BOARD SET WRITER = NULL WHERE WRITER = P_ID;
    UPDATE TBL_REPLY SET WRITER = NULL WHERE WRITER = P_ID;
    DELETE TBL_MEMBER 
    WHERE ID = P_ID;
    COMMIT;
END;
/

EXEC OUIT_PROC('kyoungbow');

SELECT * FROM TBL_MEMBER;

DELETE FROM TBL_MEMBER WHERE ID = 'gyu';
SAVEPOINT S1;
DELETE FROM TBL_MEMBER WHERE ID = 'woong3';
SAVEPOINT S2;
ROLLBACK TO S1;