--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD
--------------------------------------------------------

   CREATE SEQUENCE  "ODOUNG"."SEQ_BOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPLY
--------------------------------------------------------

   CREATE SEQUENCE  "ODOUNG"."SEQ_REPLY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_BOARD
--------------------------------------------------------

  CREATE TABLE "ODOUNG"."TBL_BOARD" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(300 BYTE), 
	"CONTENT" CLOB, 
	"HITCOUNT" NUMBER DEFAULT 0, 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"WRITER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "ODOUNG"."TBL_MEMBER" 
   (	"ID" VARCHAR2(100 BYTE), 
	"PW" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_REPLY
--------------------------------------------------------

  CREATE TABLE "ODOUNG"."TBL_REPLY" 
   (	"RNO" NUMBER, 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"REGDATE" DATE DEFAULT SYSDATE, 
	"BNO" NUMBER, 
	"WRITER" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ODOUNG.TBL_BOARD
SET DEFINE OFF;
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (1,'글 제목',3,to_date('22/03/03','RR/MM/DD'),'작성자');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (22,'123',0,to_date('22/03/07','RR/MM/DD'),'123');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (3,'수정된 글 제목',0,to_date('22/03/07','RR/MM/DD'),'작성자');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (4,'글 제목',0,to_date('22/03/03','RR/MM/DD'),'작성자');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (5,'글 제목',0,to_date('22/03/03','RR/MM/DD'),'작성자');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (6,'글 제목',0,to_date('22/03/03','RR/MM/DD'),'작성자');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (7,'글 제목',0,to_date('22/02/28','RR/MM/DD'),'작성자');
Insert into ODOUNG.TBL_BOARD (BNO,TITLE,HITCOUNT,REGDATE,WRITER) values (21,'글 제목',0,to_date('22/03/04','RR/MM/DD'),'작성자');
REM INSERTING into ODOUNG.TBL_MEMBER
SET DEFINE OFF;
Insert into ODOUNG.TBL_MEMBER (ID,PW,NAME) values ('javaman','5678','자바공주');
Insert into ODOUNG.TBL_MEMBER (ID,PW,NAME) values ('id','1234','자바남');
Insert into ODOUNG.TBL_MEMBER (ID,PW,NAME) values ('odoung','1234','오둥이');
Insert into ODOUNG.TBL_MEMBER (ID,PW,NAME) values ('amanna','1234','아맛나');
Insert into ODOUNG.TBL_MEMBER (ID,PW,NAME) values ('gyuwoong','1234','황규웅');
Insert into ODOUNG.TBL_MEMBER (ID,PW,NAME) values ('id','1234','자바남');
REM INSERTING into ODOUNG.TBL_REPLY
SET DEFINE OFF;
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (1,'댓글 내용1',to_date('22/03/08','RR/MM/DD'),1,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (2,'댓글 내용2',to_date('22/03/08','RR/MM/DD'),1,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (4,'댓글 내용4',to_date('22/03/08','RR/MM/DD'),1,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (5,'댓글 내용5',to_date('22/03/08','RR/MM/DD'),1,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (6,'댓글 내용3',to_date('22/03/08','RR/MM/DD'),3,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (7,'댓글 내용4',to_date('22/03/08','RR/MM/DD'),3,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (8,'댓글 내용5',to_date('22/03/08','RR/MM/DD'),3,'작성자');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (9,null,to_date('22/03/08','RR/MM/DD'),10,'2');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (10,'123',to_date('22/03/08','RR/MM/DD'),10,'123');
Insert into ODOUNG.TBL_REPLY (RNO,CONTENT,REGDATE,BNO,WRITER) values (11,'ASDF',to_date('22/03/08','RR/MM/DD'),12,'123');
