-- 함수 선언
-- 함수명 : GETDNAME
-- 매개변수 STUDNO
-- 반환값은 학생의 소속학과 이름
-- 반환타입은 VARCHAR2

--CREATE OR REPLACE FUNCTION GETDNAME(STUDNO NUMBER) RETURN VARCHAR2 IS
--    V_DNAME DEPARTMENT.DNAME%TYPE
--BEGIN
--
--END;
--/

SELECT DNAME 
FROM STUDENT
JOIN DEPARTMENT 
USING(DEPTNO) 
WHERE STUDNO = 10101;

CREATE OR REPLACE FUNCTION GETDNAME(P_STUDNO STUDENT.STUDNO%TYPE) RETURN DEPARTMENT.DNAME%TYPE IS
    V_DNAME DEPARTMENT.DNAME%TYPE;
BEGIN
    SELECT DNAME 
    INTO V_DNAME
    FROM STUDENT
    JOIN DEPARTMENT 
    USING(DEPTNO) 
    WHERE STUDNO = P_STUDNO;
    RETURN V_DNAME;
END;
/

SELECT GETDNAME(10101) FROM DUAL;
SELECT STUDNO, GETDNAME(STUDNO) FROM STUDENT;