CREATE TABLE T_MEMBER (
    ID VARCHAR2(10) CONSTRAINT PK_MEMBER PRIMARY KEY,
    PWD VARCHAR2(10),
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    JOINDATE DATE DEFAULT SYSDATE
);

INSERT INTO T_MEMBER VALUES('hong', '1212', 'È«±æµ¿', 'hong@mail.com', SYSDATE);
INSERT INTO T_MEMBER VALUES('lee', '1212', 'ÀÌ¼ø½Å', 'lee@test.com', SYSDATE);
INSERT INTO T_MEMBER VALUES('kim', '1212', '±èÀ¯½Å', 'kim@jweb.com', SYSDATE);

COMMIT;

SELECT * FROM T_MEMBER;

