--DBMS_XDB.SETHTTPPORT SETTER << 프로시저
--DBMS_XDB.GETHTTPPORT GETTER << 함수

SELECT DBMS_XDB.GETHTTPPORT FROM DUAL;

EXECUTE DBMS_XDB.SETHTTPPORT(9090);

-- 프로시저 선언
-- 프로시저명 MYSETHTTPPORT
-- 매개변수 NUMBER 기본값 : 10000
-- 매개변ㅅ로 지정된 값으로 HTTP PORT 변경
CREATE OR REPLACE PROCEDURE MYSETHTTPPOR (P_N NUMBER := 10000) IS
BEGIN
    DBMS_XDB.SETHTTPPORT(P_N);
END;
/

